### PR TITLE
Backend funding grouping

### PR DESCRIPTION
**Pull request by bobcaprice**

### CODE REVIEW

**Comment by bobcaprice** [comment]
[bug opening and closing work sources](https://trello.com/c/3yx0UazZ/5236-bug-opening-and-closing-work-sources)

**Comment by bobcaprice** [comment]
[Backend grouping for Funding](https://trello.com/c/oArA1OvP/5060-backend-grouping-for-funding)

**Comment by amontenegro** [comment]
@bobcaprice could you please fix this PR?

Thanks

**Comment by wjrsimpson** [comment]
@bobcaprice Merge monster!

**Pull request merged**
