### PR TITLE
Add reset password url to orcid ng

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
["Is this you?" Modal edits (3)](https://trello.com/c/4gxaWjHx/6348-is-this-you-modal-edits-3)

**Comment by leomendoza123** [comment]
[Forgotten username - do I have an ORCID ID (8)](https://trello.com/c/vGPQMWrG/6167-forgotten-username-do-i-have-an-orcid-id-8)

**Comment by amontenegro** [comment]
Hi @leomendoza123 Is this ready to go? I see the cards are still in progress

Thanks

**Comment by leomendoza123** [comment]
I was going to ask you about it tomorrow, since the card has a comment
about a pending puppet change, can we move it?

Anyway yes this is ready to be merge

**Pull request merged**
