### PR TITLE
Ng5

### PR DESCRIPTION
**Pull request by mjcalvo21**
Services with httpclient

### CODE REVIEW

**Comment by wjrsimpson** [comment]
@mjcalvo21 Please can you merge the latest master into your branch? There was a Java compilation problem (not your fault!) which is stopping Jenkins running tests on your branch.

**Comment by mjcalvo21** [comment]
[Remove ng1 code for ng2 components already live in production](https://trello.com/c/AJy1Wmhi/4838-remove-ng1-code-for-ng2-components-already-live-in-production)

**Comment by mjcalvo21** [comment]
[Keywords don't update privacy until the user clicks the save button](https://trello.com/c/opzheUQa/4668-keywords-dont-update-privacy-until-the-user-clicks-the-save-button)

**Comment by mjcalvo21** [comment]
[Ng2 Biography and funding sections are missing on /my-orcid](https://trello.com/c/EPiYtXPe/4721-ng2-biography-and-funding-sections-are-missing-on-my-orcid)

**Comment by mjcalvo21** [comment]
[Migrate Country to ng2](https://trello.com/c/UQzZwlYf/4211-migrate-country-to-ng2)

**Comment by mjcalvo21** [comment]
[/my-orcid: Also known as](https://trello.com/c/vhOOqNcr/4809-my-orcid-also-known-as)

**Comment by mjcalvo21** [comment]
[/my-orcid: Country](https://trello.com/c/aK3NuhiW/4810-my-orcid-country)

**Comment by mjcalvo21** [comment]
[/my-orcid: Biography](https://trello.com/c/hvPX1n84/4813-my-orcid-biography)

**Comment by mjcalvo21** [comment]
[/my-orcid: Also known as](https://trello.com/c/vhOOqNcr/4809-my-orcid-also-known-as)

**Pull request merged**
