### PR TITLE
Remove grant tables

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
Hey @wjrsimpson,

Please view this, we already have a liquibase script to remove those tables, but it looks we never run it before.

Thanks

**Comment by amontenegro** [comment]
[remove table funding_grant](https://trello.com/c/imY6fKAm/3947-remove-table-fundinggrant)

**Comment by amontenegro** [comment]
[remove table funding_grant](https://trello.com/c/imY6fKAm/3947-remove-table-fundinggrant)

**Comment by wjrsimpson** [comment]
@amontenegro Looks good to me. Cheers.

**Pull request merged**
