### PR TITLE
Fixing error where the the url was interpreted as a relative path

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/VbvLlqHv/2103-when-adding-a-custom-url-to-an-identifier-the-url-is-formatted-to-start-with-orcid-org

**Comment by rcpeters** [comment]
Deploy to qa.

**Comment by amontenegro** [comment]
@rcpeters am waiting for @hexplus to fix the search bug.

**Comment by rcpeters** [comment]
That's for next release. Unless he say's it's really fast.

**Comment by amontenegro** [comment]
Ok, moving this to QA and the other will go in the next release

**Pull request merged**
