### PR TITLE
Enable authentication on pub api

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
Card: https://trello.com/c/GXxn5Qhg/1978-move-public-search-under-the-public-client

Step #1: Enable member authentication in public api

Hey @rcpeters, Step # 2 of this project will be to enable the member authentication on API V2, do you want to move step # 1 first or you want to move to QA when everything is ready?

**Comment by rcpeters** [comment]
We'll wait until both work the same.

**Comment by rcpeters** [comment]
@amontenegro Is the member side still pending?

**Comment by amontenegro** [comment]
https://trello.com/c/GXxn5Qhg/1978-move-public-search-under-the-public-client

**Comment by amontenegro** [comment]
@rcpeters this is ready to go!

**Pull request merged**
