### PR TITLE
[3862] Security update: removing target _blank from links in the project

### PR DESCRIPTION
**Pull request by mjcalvo21**
https://trello.com/c/wuXHdIQU/3862-no-targetblank-in-the-registry-codebase

### CODE REVIEW

**Comment by mjcalvo21** [comment]
[No target="_blank" in the registry codebase](https://trello.com/c/wuXHdIQU/3862-no-targetblank-in-the-registry-codebase)

**Comment by rcpeters** [comment]
sorry if I wasn't clear enough. We can use new windows, they should be renamed. `target="_blank">${springMacroRequestContext.getMessage("2FA.learn_more_link")}<` should be something like `target="2FA.learn_more_link">${springMacroRequestContext.getMessage("2FA.learn_more_link")}<`

**Comment by mjcalvo21** [comment]
Closing while code is updated with the latest request

**Comment by rcpeters** [comment]
Nice job with the regex

**Pull request merged**
