### PR TITLE
Add caching to funding

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/KMEXoQp7/2558-orcid-web-fundings-fundingids-json-isn-t-caching-properly

**Comment by rcpeters** [comment]
:+1:

**Comment by amontenegro** [comment]
Hey @rcpeters, 

Here I did the following changes: 

1) Changed the FundingController and FundingForm(And childs) objects to work with the latest rc2 code, which will help us to reduce a lot of code in the controller
2) Added cache to the ProfileFundingManagerImpl for the Fundings and Fundings summaries

**Comment by amontenegro** [comment]
https://trello.com/c/cAnzqejS/2561-add-caching-to-funding

**Pull request merged**
