### PR TITLE
Rc4 branch

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
Please dont merge yet! Still need to run BB tests

**Comment by amontenegro** [comment]
[V2.0_rc4](https://trello.com/c/3OlNXLSk/3202-v2-0-rc4)

**Comment by amontenegro** [comment]
PLEASE DONT MERGE YET!

**Comment by amontenegro** [comment]
Hi @wjrsimpson! This is now ready to go! lets see if @caoyler want to move it to this release or to the next one.

Thanks

**Comment by amontenegro** [comment]
[V2.0_rc4](https://trello.com/c/3OlNXLSk/3202-v2-0-rc4)

**Comment by rcpeters** [comment]
merge monster

**Comment by amontenegro** [comment]
Hey @rcpeters this is fixed, please merge.

Thanks

**Comment by amontenegro** [comment]
Close to test the CI server

**Pull request closed without merging**
