### PR TITLE
RDF: Split/fix URI for account and profile document

### PR DESCRIPTION
**Pull request by stain**
This assumes pull requests #2473 and #2474 to get updated Jena and JSON-LD/N-Triple support. #2472 should also be included for correct `303 See Other` response.

As discussed with @TomDemeranville in [ORCID RDF telcon](https://gist.github.com/stain/abaf89cf40df2823dde1) and the [ORCID semantics comments](http://www.w3.org/2015/03/orcid-semantics) by @philarcher1.

This changes to use these distinct URIs:

* Person: http://orcid.example.com/000-1337 
* Publications: http://orcid.example.com/000-1337#workspace-works
* Account: http://orcid.example.com/000-1337#orcid-id
* Personal profile document: http://pub.orcid.example.com/experimental_rdf_v1/000-1337

The two `#anchor` URIs correspond to those sections in the HTML, see for example http://orcid.org/0000-0001-9842-9718#workspace-works and http://orcid.org/0000-0001-9842-9718#orcid-id

I've not tested if the code gives the correct URI for the `foaf:PersonalProfileDocument` as I would need to test it in a production system to get a real `UriInfo` injected - the test uses one from Mockito.

New output would be for instance (condensed):

```turtle
@prefix pav:   <http://purl.org/pav/> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix gn:    <http://www.geonames.org/ontology#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .

<http://orcid.example.com/000-1337>
        a                  foaf:Person , prov:Person ;
        rdfs:label         "John Doe" ;
        foaf:account       <http://orcid.example.com/000-1337#orcid-id> ;
        foaf:homepage      <http://example.com/myPage> ;
        foaf:publications  <http://orcid.example.com/000-1337#workspace-works> .

<http://orcid.example.com/000-1337#workspace-works>
        a       foaf:Document .

<http://orcid.example.com/000-1337#orcid-id>
        a                            foaf:OnlineAccount ;
        rdfs:label                   "000-1337" ;
        foaf:accountName             "000-1337" ;
        foaf:accountServiceHomepage  <http://orcid.org> .

<http://pub.orcid.example.com/experimental_rdf_v1/000-1337>
        a                     foaf:PersonalProfileDocument ;
        pav:createdBy         <http://orcid.example.com/000-1337> ;
        pav:createdWith       <http://orcid.org> ;
        pav:lastUpdateOn      "1980-12-31T23:29:29.999Z"^^xsd:dateTime ;
        prov:generatedAtTime  "1980-12-31T23:29:29.999Z"^^xsd:dateTime ;
        prov:wasAttributedTo  <http://orcid.example.com/000-1337> ;
        foaf:primaryTopic     <http://orcid.example.com/000-1337> .
```

Is this how you were thinking, @philarcher1? Perhaps @iherman also would like to check.

### CODE REVIEW

**Comment by TomDemeranville** [comment]
Hi Stian,

I'd like to rename #workspace-works
<http://orcid.example.com/000-1337#workspace-works> #activities.

I've modified your example to include this and also to use real orcid.org
URIs.  Can you confirm this is correct?

<http://orcid.org/0000-0000-0000-1234>
        a                  foaf:Person , prov:Person ;
        rdfs:label         "John Doe" ;
        foaf:account       <http://orcid.org/0000-0000-0000-1234#orcid-id> ;
        foaf:homepage      <http://example.com/myPage> ;
        foaf:publications  <http://orcid.org/0000-0000-0000-1234#activities>
.

<http://orcid.org/0000-0000-0000-1234#activities>
        a       foaf:Document .

<http://orcid.org/0000-0000-0000-1234#orcid-id>
        a                            foaf:OnlineAccount ;
        rdfs:label                   "0000-0000-0000-1234" ;
        foaf:accountName             "0000-0000-0000-1234" ;
        foaf:accountServiceHomepage  <http://orcid.org> .

<http://pub.orcid.org/experimental_rdf_v1/000-1337>
        a                     foaf:PersonalProfileDocument ;
        pav:createdBy         <http://orcid.org/0000-0000-0000-1234> ;
        pav:createdWith       <http://orcid.org> ;
        pav:lastUpdateOn      "1980-12-31T23:29:29.999Z"^^xsd:dateTime ;
        prov:generatedAtTime  "1980-12-31T23:29:29.999Z"^^xsd:dateTime ;
        prov:wasAttributedTo  <http://orcid.org/0000-0000-0000-1234> ;
        foaf:primaryTopic     <http://orcid.org/0000-0000-0000-1234> .

At some point we need to update the nginx and jersey routing to remove the
experimental from experimental_rdf_v1.  Ideally, in my mind, we will simply
point it at the v1.2 API.  Any thoughts Rob?

Best,

Tom.

**Comment by amontenegro** [comment]
Can one of the admins verify this patch?

**Comment by rcpeters** [comment]
@amontenegro what are up asking? Yes we can merge if it works and doesn't break anything.

**Comment by stain** [comment]
Right, the example looks as I would expect. I just pasted the output of the test, which uses an `example.org` hostname to ensure it is parametrized correctly.

There's also `http` vs `https` - I think the RDF should always use `http` for the ORCID itself - which I believe is what you get back as getURI() on the orcid - the experimental_rdf one would however reflect whatever you requested, which I think is fine. Something to test on staging server though.

Renaming `#workspace-works` is fine with me, but there is currently no `id="activities"` in the HTML rendering - so the hyperlink would then be misleading. `#workspace-works` takes you to the actual works/publication list. 

See also [work_section_header_inc_v3.ftl](https://github.com/ORCID/ORCID-Source/blob/master/orcid-web/src/main/resources/freemarker/includes/work/work_section_header_inc_v3.ftl#L22)

You might also want to change from `<a name="">` to <div id="">`

**Pull request merged**
