### PR TITLE
When chaning the org name, remove the disambiguated org and display t…

### PR DESCRIPTION
**Pull request by amontenegro**
…he typeahead again

### CODE REVIEW

**Comment by amontenegro** [comment]
@wjrsimpson could you please take a look at this one?

**Comment by amontenegro** [comment]
https://trello.com/c/FlXHGxPI/2593-for-affiliations-added-manually-in-the-ui-org-disambiguated-id-isn-t-changed-if-the-org-is-edited

**Comment by rcpeters** [comment]
We need to talk to @Laura-ORCID before making this change.

**Comment by amontenegro** [comment]
Ok, lets close this until we define what we want to do here.

FYI @rcpeters @Laura-ORCID

**Pull request closed without merging**
