### PR TITLE
remove encrypting session variable

### PR DESCRIPTION
**Pull request by rcpeters**
@amontenegro I didn't see a reason for encrypting, is there one?

### CODE REVIEW

**Comment by amontenegro** [comment]
Hey @rcpeters is ok to merge it without encrypting it; but, before that, could you please add those changes to OauthConfirmAccessController.registerAndAuthorize, it also have the same problem



Thanks

**Comment by rcpeters** [comment]
@amontenegro Go ahead and make those changes as it's my day off. @wjrsimpson can merge. We should be ready to spot any other similar issues where we assumed an encrypted string was a hash.

**Comment by amontenegro** [comment]
Hey @wjrsimpson, this is done, could yuo please merge/deploy? thanks

**Comment by wjrsimpson** [comment]
https://trello.com/c/OQOuU47y/2467-not-possible-to-register-on-qa

**Pull request merged**
