### PR TITLE
Openid discovery

### PR DESCRIPTION
**Pull request by TomDemeranville**
This works in manual testing, but I cannot get the integration tests to work at the moment.

### CODE REVIEW

**Comment by TomDemeranville** [comment]
[Investigate openid discovery and see if we can support it with minimal effort. Use this to configure third party test tool.](https://trello.com/c/h6iStwhZ/3791-investigate-openid-discovery-and-see-if-we-can-support-it-with-minimal-effort-use-this-to-configure-third-party-test-tool)

**Comment by wjrsimpson** [comment]
@TomDemeranville There are merge conflicts in your pull request. I am guessing you didn't want to commit changes to localhost.webpack.config.js?

**Comment by TomDemeranville** [comment]
@wjrsimpson there is a problem with that file being in git as it contains local config information (if you want it to deploy to tomcat).  I will update so that it modifies the local source tree and re-commit.  Not sure what else to do.

**Comment by wjrsimpson** [comment]
@TomDemeranville Sorry Tom, more conflicts!

**Pull request merged**
