### PR TITLE
Affiliation search

### PR DESCRIPTION
**Pull request by TomDemeranville**
https://trello.com/c/7OywbDz8/3102-sustain-user-feature-affiliation-search

I've put two identifier indexes in place.  
- ringgold-org-id 
- fundref-org-id 

I've put two name indexes in place:
- funding-org-name
- affiliation-org-name (for education and employment)

(Note that the names are not disambiguated versions)

I've also enabled 'grant-numbers' and 'funding-title' indexes.

### CODE REVIEW

**Comment by TomDemeranville** [comment]
[SUSTAIN: USER FEATURE: Affiliation search](https://trello.com/c/7OywbDz8/3102-sustain-user-feature-affiliation-search)

**Comment by amontenegro** [comment]
This PR should move together with https://github.com/ORCID/ORCID-Source/pull/3263

**Comment by rcpeters** [comment]
@TomDemeranville can we get this one merged up?

**Comment by rcpeters** [comment]
ping

**Pull request merged**
