### PR TITLE
Check if the existing token is not disabled

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/egXuPh6Q/2984-authorization-page-is-skipped-when-there-is-a-revoked-token-with-the-same-scopes

**Comment by rcpeters** [comment]
@amontenegro can you also add a test that cover this?

**Comment by amontenegro** [comment]
Yes sir, working on it @rcpeters

**Comment by amontenegro** [comment]
Hey @rcpeters, this is ready to go!

**Pull request merged**
