### PR TITLE
Make default privacy apply to entire record

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/3yxB47va/2668-make-default-privacy-apply-to-the-entire-record

**Comment by rcpeters** [comment]
Hum, there are test that would need to be revised before this work would be considered complete.

**Comment by amontenegro** [comment]
Hey @rcpeters, which test are you talking about?

**Comment by rcpeters** [comment]
Explain this:
https://github.com/ORCID/ORCID-Source/pull/2705

**Pull request merged**
