### PR TITLE
Fix bio put source

### PR DESCRIPTION
**Pull request by wjrsimpson**
https://trello.com/c/R10qeFXe/2672-common-source-name-set-to-null-when-updating-bio-items-with-1-2

### CODE REVIEW

**Comment by wjrsimpson** [comment]
@amontenegro Angel, please can you review these changes? Cheers.

**Comment by amontenegro** [comment]
sure! looking at this now

**Comment by amontenegro** [comment]
Hey @wjrsimpson, 

Change to Jaxb2JpaAdapterImpl seems to be fine, however, I dont see any changes to 

MapperFacadeFactory.addV2SourceMapping where the original issue comes from.

Look at card: https://trello.com/c/R10qeFXe/2672-common-source-name-set-to-null-when-updating-bio-items-with-1-2

If you look at how we are mapping the source there: 

`private void addV2SourceMapping(MapperFactory mapperFactory) {
        mapperFactory.classMap(org.orcid.jaxb.model.common_rc2.Source.class, SourceEntity.class).fieldAToB("sourceOrcid.path", "sourceProfile.id")
                .fieldAToB("sourceClientId.path", "sourceClient.id").customize(new CustomMapper<org.orcid.jaxb.model.common_rc2.Source, SourceEntity>() {
                    @Override
                    public void mapBtoA(SourceEntity sourceEntity, org.orcid.jaxb.model.common_rc2.Source source, MappingContext context) {
                        String sourceId = sourceEntity.getSourceId();
                        if (OrcidStringUtils.isClientId(sourceId)) {
                            SourceClientId sourceClientId = new SourceClientId(sourceId);
                            sourceClientId.setHost(orcidUrlManager.getBaseHost());
                            sourceClientId.setUri(orcidUrlManager.getBaseUriHttp() + "/client/" + sourceId);
                            source.setSourceClientId(sourceClientId);
                        } else {
                            SourceOrcid sourceOrcid = new SourceOrcid(sourceId);
                            sourceOrcid.setHost(orcidUrlManager.getBaseHost());
                            sourceOrcid.setUri(orcidUrlManager.getBaseUriHttp() + "/" + sourceId);
                            source.setSourceOrcid(sourceOrcid);
                        }
                    }
                }).byDefault().register();
    }`

Specifically in:  if (OrcidStringUtils.isClientId(sourceId)), if we send a sourceId that looks like an orcid id, it will return a "SourceOrcid", so, when we try to map the client name we try to get the info from the profile table, but, for many clients, the info is not there, so, we return an empty source.

I think we should improve MapperFacadeFactory.addV2SourceMapping to check not for OrcidStringUtils.isClientId, instead, it should go to the client_details table and check if the client is there, if it is, return a SourceClientId, if it isnt, then return a SourceOrcid

Please let me know if you have any question.

Thanks

**Comment by amontenegro** [comment]
Everything is ok now, ready to merge

**Pull request merged**
