### PR TITLE
POSTs to /reset-password.json with params in the URL now returned a 4…

### PR DESCRIPTION
**Pull request by bobcaprice**
…22 response

### CODE REVIEW

**Comment by bobcaprice** [comment]
[Throw http 422 when unexpected parameters are sent to /reset-password.json](https://trello.com/c/PY6rpQta/3700-throw-http-422-when-unexpected-parameters-are-sent-to-reset-password-json)

**Comment by rcpeters** [comment]
@bobcaprice did you test this in the UI? Your javascript does send `_` examle `https://orcid.org/password-reset.json?_=1494019562865`

**Comment by bobcaprice** [comment]
@rcpeters Yeah I did test the UI, but didn't see any _=... - I think that's something JQuery sometimes appends, do you want _ param to be allowed?

**Comment by bobcaprice** [comment]
@rcpeters _ parameter now allowed

**Pull request merged**
