### PR TITLE
Lets reuse the existing entity, instead of creating a new one just to…

### PR DESCRIPTION
**Pull request by amontenegro**
… copy over the values

### CODE REVIEW

**Comment by amontenegro** [comment]
[Prod: Updating an item changes the create date](https://trello.com/c/Uw8foCmd/6372-prod-updating-an-item-changes-the-create-date)

**Comment by lizkrznarich** [comment]
@amontenegro Can you please have a look at the merge conflict?

**Comment by amontenegro** [comment]
@lizkrznarich merge monster!

**Comment by amontenegro** [comment]
@lizkrznarich fixed

**Pull request merged**
