### PR TITLE
Fix validation errors

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/L9n9uWJ5/2792-consistent-location-of-create-modified-dates-and-source

**Comment by amontenegro** [comment]
https://trello.com/c/3z0fDh6q/2796-rc2-biography-should-the-content-be-in-personal-details-content-or-record-content

**Comment by amontenegro** [comment]
https://trello.com/c/GpNqucU3/2783-rc2-validation-errors-for-last-modified-date-on-person-name-and-biography

**Comment by rcpeters** [comment]
👍

**Comment by amontenegro** [comment]
https://trello.com/c/0dfOwpwv/2785-rc2-record-employment-vs-affiliation-namespace

**Comment by amontenegro** [comment]
https://trello.com/c/OfBxYLg1/2786-rc2-record-email-and-address-invalid-if-returned-empty

**Comment by amontenegro** [comment]
https://trello.com/c/0dfOwpwv/2785-rc2-record-employment-vs-affiliation-namespace

**Pull request merged**
