### PR TITLE
Ga event tracking to features

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
Hi @lizkrznarich, could you please take a look?

I moved the OrcidGA code to its own js file, and, import it in the html-head.ftl file so it is accessible from the scripts generated by the freemarker templates 

Thanks

**Comment by amontenegro** [comment]
[Add GA event tracking to features](https://trello.com/c/t3K97XFc/3912-add-ga-event-tracking-to-features)

**Comment by rcpeters** [comment]
@amontenegro why did you have to move this to it's own file?

**Comment by amontenegro** [comment]
@rcpeters because the macro to show/hide features checkFeatureStatus could be used anywhere in the code, even before the script.js is loaded, so, in order to be able to use the OrcidGA function, we need to load that function as soon as possible in the code, hence, I move it to its own script file and load that file in the header, so, it is ready for any call to the checkFeatureStatus macro

**Comment by rcpeters** [comment]
@amontenegro @lizkrznarich we don't need yet another javascript browser request. You can put in a freemarker file and do a freemarker include.

**Comment by amontenegro** [comment]
great idea, I just moved the script to a freemarker file @rcpeters

**Comment by lizkrznarich** [comment]
@amontenegro @rcpeters I can buy that.

**Pull request merged**
