### PR TITLE
Per activity api activities update

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/dFU1fdmI/3-add-scope-person-update
https://trello.com/c/ZXXa8VOu/2-add-scope-activities-update

**Comment by amontenegro** [comment]
Hey @rcpeters,

A couple of things here: 

1) This request includes the two new scopes /activities/update and /person/update
2) For /person/update I just make it work as /orcid-bio/update, let me know if it should also include the ability to update ext ids 
3) Please check PerActivityAPINewScopesTest.java, it is a "new" kind of integration test, that will create the data it need, and then, it will delete it
4) I added a new creation method in CreationMethod.java **INTEGRATION_TEST** so, all users that are created in an integration tests will belong to this category

Thanks

**Comment by rcpeters** [comment]
@amontenegro Yes include externalIdentifiers under /person/update. You might also audit what is person-2.0_rc1.xsd on branch 1.3_rc1.

**Comment by amontenegro** [comment]
@rcpeters cool! I will let you know when it is ready to merge

**Comment by amontenegro** [comment]
Hey @rcpeters,

This is ready, you can merge it whenever you want.

Thanks

**Pull request merged**
