### PR TITLE
Check if GA is enabled before pushing an event

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
Pull request 2500!!!!

**Comment by amontenegro** [comment]
https://trello.com/c/akOaVxSQ/2468-check-if-google-analitycs-is-enable-just-before-sending-an-event

**Comment by rcpeters** [comment]
@wjrsimpson @amontenegro Please see  https://developers.google.com/analytics/devguides/collection/analyticsjs/?hl=en
GA should always be available. The root issue looks like we also testing for ga.create which may not be true. We should always be pushing to qa regardless of "create". However it also looks like do to how UA has changed we need to call trackArray(); if ga.create isn't there.

**Comment by wjrsimpson** [comment]
@rcpeters Makes sense, cheers.

**Pull request merged**
