### PR TITLE
Fasterxml

### PR DESCRIPTION
**Pull request by rcpeters**

### CODE REVIEW

**Comment by rcpeters** [comment]
@amontenegro can you test this locally?

**Comment by amontenegro** [comment]
@rcpeters I tested the following: 

1) Adding works using the UI and API
2) Read from public and member API
3) Check that solr index fine the updated profiles

Is there anything else you want me to test?

Also, please merge monster in case you think what I did tests all you want to test

**Comment by rcpeters** [comment]
No that's great. We'll put it on the next release.

On Wed, Mar 18, 2015 at 12:41 PM, Angel Montenegro <notifications@github.com
> wrote:

> @rcpeters <https://github.com/rcpeters> I tested the following:
>
> 1) Adding works using the UI and API
> 2) Read from public and member API
> 3) Check that solr index fine the updated profiles
>
> Is there anything else you want me to test?
>
> Also, please merge monster in case you think what I did tests all you want
> to test
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ORCID/ORCID-Source/pull/1890#issuecomment-83135554>.
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by rcpeters** [comment]
@amontenegro you'll need to make sure @hexplus instance works next time he pulls from master. @wjrsimpson FYI.

**Pull request merged**
