### PR TITLE
Affiliations v3 ui fixes

### PR DESCRIPTION
**Pull request by lizkrznarich**

### CODE REVIEW

**Comment by lizkrznarich** [comment]
[New affiliations: extra commas and line breaks with other org ids](https://trello.com/c/W2Pxd6Tz/5083-new-affiliations-extra-commas-and-line-breaks-with-other-org-ids)

**Comment by lizkrznarich** [comment]
[Display the affiliation type in the UI](https://trello.com/c/T9xtFDR1/4930-display-the-affiliation-type-in-the-ui)

**Comment by lizkrznarich** [comment]
[New affiliations display: All org links go to https://qa.orcid.org/link](https://trello.com/c/jaEuoZxp/5087-new-affiliations-display-all-org-links-go-to-https-qaorcidorg-link)

**Comment by lizkrznarich** [comment]
[Grouped affiliations only show one version in the UI](https://trello.com/c/n6HZbv4r/5079-grouped-affiliations-only-show-one-version-in-the-ui)

**Comment by wjrsimpson** [comment]
@lizkrznarich merge monster!

**Pull request merged**
