### PR TITLE
Add accessibility menu

### PR DESCRIPTION
**Pull request by leomendoza123**
please merge #5528 first

### CODE REVIEW

**Comment by leomendoza123** [comment]
[Add the translations of the new app on transifex](https://trello.com/c/WwQKxIfk/6037-add-the-translations-of-the-new-app-on-transifex)

**Comment by leomendoza123** [comment]
[Accesibility support](https://trello.com/c/j05goeno/6034-accesibility-support)

**Comment by leomendoza123** [comment]
[Search bar states](https://trello.com/c/f9hwF5jE/6105-search-bar-states)

**Comment by leomendoza123** [comment]
[New header: Fix focus state on language selector and search dropdown (Drupal and registry)](https://trello.com/c/AMxCwsQ8/6133-new-header-fix-focus-state-on-language-selector-and-search-dropdown-drupal-and-registry)

**Comment by lizkrznarich** [comment]
@leomendoza123 Please resolve merge conflicts

**Pull request merged**
