### PR TITLE
fix: Add missing create event method for social sign in

### PR DESCRIPTION
**Pull request by DanielPalafox**

### CODE REVIEW

**Review by amontenegro — APPROVED** [review]

**Comment by DanielPalafox** [comment]
[[QA] Issues capturing OAuth events within the registry](https://trello.com/c/VsCZnc9r/8892-qa-issues-capturing-oauth-events-within-the-registry)

**Comment by DanielPalafox** [comment]
[[QA] Issues capturing institutional and social signin events within the registry](https://trello.com/c/pJsqXRei/8893-qa-issues-capturing-institutional-and-social-signin-events-within-the-registry)

**Comment by DanielPalafox** [comment]
[[QA] 500 error from authorize.json when  doing OAuth with third-party signin](https://trello.com/c/6HNDLDiG/8891-qa-500-error-from-authorizejson-when-doing-oauth-with-third-party-signin)

**Comment by DanielPalafox** [comment]
[[QA] Do not capture authorization code for registry Reauthorize event](https://trello.com/c/f8L0FGHg/8895-qa-do-not-capture-authorization-code-for-registry-reauthorize-event)

**Comment by DanielPalafox** [comment]
[[QA] Registry event captured for OAuth new registration needs fixing](https://trello.com/c/jbdfmzfE/8894-qa-registry-event-captured-for-oauth-new-registration-needs-fixing)

**Pull request merged**
