### PR TITLE
Ng2 migration.v.0.4

### PR DESCRIPTION
**Pull request by mjcalvo21**
https://trello.com/c/swcDNtxb/4082-migrate-biography-to-ng2

### CODE REVIEW

**Comment by mjcalvo21** [comment]
[Migrate Biography to ng2](https://trello.com/c/swcDNtxb/4082-migrate-biography-to-ng2)

**Comment by lizkrznarich** [comment]
@mjcalvo21 Instead of taking out the privacy toggle macro in ng2 biography template, need to make an Ng2 version of privacyToggle2 macro, similar to privacyToggle3Ng2 https://github.com/ORCID/ORCID-Source/pull/3982/files#diff-dbf19754366312f44baf161633604c29R336

**Comment by lizkrznarich** [comment]
[Migrate WorksPrivacyPreferencesCtrl.ts to angular2](https://trello.com/c/u1TA7SMx/3967-migrate-worksprivacypreferencesctrlts-to-angular2)

**Comment by mjcalvo21** [comment]
[Migrate Biography to ng2](https://trello.com/c/swcDNtxb/4082-migrate-biography-to-ng2)

**Pull request merged**
