### PR TITLE
Added Google Analytics tracking for social log in.

### PR DESCRIPTION
**Pull request by wjrsimpson**
https://trello.com/c/98qnHnQg/2425-social-login-google-analytics-tracking

### CODE REVIEW

**Comment by wjrsimpson** [comment]
@amontenegro Angel, please can you review these changes, and check they are compatible with your refactoring of the OAuth controller?

**Comment by amontenegro** [comment]
@wjrsimpson sure! let me take a look

**Comment by amontenegro** [comment]
@wjrsimpson looks good to me! you want to have this in this release or we should merge later?

**Comment by wjrsimpson** [comment]
@amontenegro Thanks! Let's wait until the next release.

**Pull request merged**
