### PR TITLE
Cleanup unclaimed emails

### PR DESCRIPTION
**Pull request by auumgn**

### CODE REVIEW

**Comment by auumgn** [comment]
[Remove emails associated to unclaimed records](https://trello.com/c/D7Nd6bNL/7472-remove-emails-associated-to-unclaimed-records)

**Comment by amontenegro** [comment]
@auumgn great job here man, however, you are missing one thing, you havent cleaned the properties keys that are not used anymore, please take a look at that as well.

Thanks

**Review by amontenegro — CHANGES_REQUESTED** [review]
@auumgn great job here man, however, you are missing one thing, you havent cleaned the properties keys that are not used anymore, please take a look at that as well.

Thanks

**Comment by amontenegro** [comment]
@auumgn lets ingore my last comment, we will work on a script for the cleanup in a near future.

Thanks

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
