### PR TITLE
Manage members migration

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
Please merge clientEditNg2 before merging this PR

**Comment by leomendoza123** [comment]
[/manage-members](https://trello.com/c/iALuAT2k/5214-manage-members)

**Comment by wjrsimpson** [comment]
@leomendoza123 Please take a look at the merge conflicts.

**Comment by leomendoza123** [comment]
@lizkrznarich Hi Liz. I did already remove the elements.

**Comment by wjrsimpson** [comment]
@leomendoza123 Please can you fix the merge conflicts.

**Pull request merged**
