### PR TITLE
Read only manager for v2

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
[For PUB and MEMBERS API: Use replication database for view/read operations](https://trello.com/c/fgI6KqYg/3201-for-pub-and-members-api-use-replication-database-for-view-read-operations)

**Comment by amontenegro** [comment]
Lest not merge this yet, we still need some changes so we use the replication DB to read from pub and members api.

**Comment by amontenegro** [comment]
This is ready to go now

**Comment by rcpeters** [comment]
merge monster

**Comment by amontenegro** [comment]
I need to run BB tests for this one, so, lets not merge it yet.

**Comment by amontenegro** [comment]
Hi @rcpeters this is ready to go.

Thanks

**Pull request merged**
