### PR TITLE
Added the organization XmlElement

### PR DESCRIPTION
**Pull request by nitw-shobhit**
https://trello.com/c/t4o7aZwL/1989-organization-missing-from-curl-v-http-pub-orcid-org-v2-0-rc1-0000-0003-3188-6273-activities

### CODE REVIEW

**Comment by rcpeters** [comment]
Missing from XSD.

**Comment by rcpeters** [comment]
Also it's named `organization` not `org`. Summary names should match the actual objects names. Finally the sample xml should be updated.

**Comment by nitw-shobhit** [comment]
The name of the object was org in the entity. Name needs to match in both JPA and JAXB.

**Comment by nitw-shobhit** [comment]
the XML interprets it as 'organization'
capture

**Comment by rcpeters** [comment]
1. Update java have same member name and XML name spaces as /orcid-model/src/main/java/org/orcid/jaxb/model/record/Employment.java
2. Add new element to XSD (located in /orcid-model/src/main/resources/record_2.0_rc1)
3. Add new element to XML Samples (located in /orcid-model/src/main/resources/record_2.0_rc1/samples).
4. Verify test still work.

**Pull request merged**
