### PR TITLE
Create record element

### PR DESCRIPTION
**Pull request by amontenegro**

### CODE REVIEW

**Comment by amontenegro** [comment]
https://trello.com/c/eKcR2Ddp/2599-curl-k-https-pub-qa-orcid-org-v2-0-rc2-0000-0002-2062-6815-returns-nothing

https://trello.com/c/JKC30ctD/2525-curl-http-pub-qa-orcid-org-v2-0-rc2-0000-0002-2062-6815-return-nothing

**Comment by rcpeters** [comment]
@amontenegro are the test stable on this?

**Comment by amontenegro** [comment]
Hey @rcpeters not yet, am still working on fixing some unit tests that fails due the read_public scope change we did last week.

Am working on fixing them.

Thanks

**Comment by amontenegro** [comment]
Hey @rcpeters this is ready to go!

**Pull request merged**
